# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin VanEvery
email: kevin@kevinvanevery.com
description: Design, development, writing, project management, consulting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevinvanevery.com" # the base hostname & protocol for your site
twitter_username: kvanever
github_username:  kvanever

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js]
